In [1]:
import numpy as np
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [2]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#(rows,cols)
arr2d.shape

(2, 3)

In [4]:
#dimensions
arr2d.ndim

2

In [5]:
#Total elements
arr2d.size

6

In [6]:
#Data type => int32 or int64
arr2d.dtype

dtype('int64')

In [7]:
#indexing or slicing
arr[0]

np.int64(10)

In [8]:
#negative indexing
arr[-1]

np.int64(40)

In [9]:
#same output as arr[0]
arr[-4]

np.int64(10)

In [10]:
#slicing
arr[1:4]

array([20, 30, 40])

In [11]:
arr2d[0,1]

np.int64(2)

In [12]:
arr2d[1,:]

array([4, 5, 6])

In [13]:
arr2d[:,2]

array([3, 6])

In [14]:
#practice
r = np.array([100,200,300,400,500])
r[1:4]

array([200, 300, 400])

In [15]:
#practice
r2 = np.array([[11,12,13],[21,22,23]])
r2[0,:]

array([11, 12, 13])

In [16]:

#practice
r2[0:2,0]

array([11, 21])

In [17]:
#practice
r2[1,1]

np.int64(22)

In [18]:
#Special Arrays in NumPy 
#2x3 array with all 0s
ze = np.zeros((2,3))
ze

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
 # 3x2 array with all 1s
on = np.ones((3,2))  
on

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# 3x3 Identity matrix
id = np.eye(3, 3)  # on = np.ones(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# 2x2 array filled with 7
fu = np.full((2,2),7)
fu

array([[7, 7],
       [7, 7]])

In [22]:
# [0 2 4 6 8]
ar = np.arange(0,10,2)
ar

array([0, 2, 4, 6, 8])

In [23]:
# 5 numbers from 0 to 1 evenly spaced
lin = np.linspace(0,1,5)
lin

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
#practice
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#practice
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [26]:
#practice
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#practice
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [28]:
#practice
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [29]:
#Boolean indexing
arr>20

array([False, False,  True,  True])

In [30]:
(arr[arr>20])

array([30, 40])

In [31]:
#practice
(arr[arr>18])

array([20, 30, 40])

In [32]:
#practice
(arr[arr>=20])

array([20, 30, 40])

In [33]:
#practice
(arr[arr % 2 == 0])

array([10, 20, 30, 40])

In [34]:
#practice
(arr[arr % 2 != 0])

array([], dtype=int64)

In [35]:
#practice
(arr[arr % 3 == 0])

array([30])

In [36]:
# practice
(arr[(arr > 20) & (arr < 40)])

array([30])

In [37]:
# Array reshaping
a = np.array([1,2,3,4,5,6])
b = a.reshape((2,3))
b


array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
#practice
nums = np.array([1,2,3,4,5,6,7,8])


In [39]:
#practice
rau = nums.reshape((2, 4))
rau

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
#practice transpose
rau.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [41]:
#practice convert 1D array
rau.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
#Random Integers
np.random.randint(1,10)

3

In [43]:
np.random.randint(1,100, size = 5)

array([10, 46, 85,  4, 99], dtype=int32)

In [44]:
#Random floats
np.random.rand(3)

array([0.39226099, 0.21339378, 0.16368135])

In [45]:
np.random.rand(2,3)

array([[0.0163147 , 0.85941145, 0.14411998],
       [0.86288322, 0.4916383 , 0.56723864]])

In [46]:
#Random from Normal Distribution 
np.random.randn(4)

array([-1.93629469,  0.33633563, -0.55111087,  1.38796045])

In [47]:
#Shuffle & Choice
np.random.shuffle(arr)
arr

array([10, 40, 20, 30])

In [48]:
np.random.choice(arr)
np.random.choice(arr,size=3,replace=False)

array([40, 20, 10])

In [49]:
#Seed (Fixed randomness)
np.random.seed(42)
np.random.randint(1,10)

7

In [50]:
#practice
np.random.randint(10,50,size = 6)

array([38, 24, 17, 30, 48, 28], dtype=int32)

In [51]:
#practice
np.random.rand(3,3)

array([[9.99749158e-02, 4.59248892e-01, 3.33708611e-01],
       [1.42866818e-01, 6.50888473e-01, 5.64115790e-02],
       [7.21998772e-01, 9.38552709e-01, 7.78765841e-04]])

In [52]:
#practice
np.random.shuffle(arr)
arr

array([40, 20, 10, 30])

In [53]:
np.random.choice(arr,size = 2)

array([30, 20])

In [54]:
np.random.seed(42)
np.random.randint(1,10)

7

In [55]:
#union
array1 = np.array([2, 5, 2, 8, 5, 8, 8])
unique_value = np.unique(array1)
unique_value

array([2, 5, 8])

In [56]:
#where
result = np.where(arr>20)
result #return index that elements
arr[result]  #return elements

array([40, 30])

In [57]:
# axis
np.sum(arr2d, axis=0)  #column wise

array([5, 7, 9])

In [58]:
np.sum(arr2d,axis=1) # rows wise

array([ 6, 15])

In [59]:
#math function
np.mean(arr)

np.float64(25.0)

In [60]:
np.mean(arr2d)

np.float64(3.5)

In [61]:
np.min(arr2d)

np.int64(1)

In [62]:
np.max(arr)

np.int64(40)

In [63]:
np.std(arr2d)

np.float64(1.707825127659933)

In [64]:
#np.stack() / vstack() / hstack()
a = np.array([1,2,3])
b = np.array([4,5,6])
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])